/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_arianjm_tfg_deskvoice_CommandControl */

#ifndef _Included_com_arianjm_tfg_deskvoice_CommandControl
#define _Included_com_arianjm_tfg_deskvoice_CommandControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_arianjm_tfg_deskvoice_CommandControl
 * Method:    multimediaKey
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_arianjm_tfg_deskvoice_CommandControl_multimediaKey
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_arianjm_tfg_deskvoice_CommandControl
 * Method:    press
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_arianjm_tfg_deskvoice_CommandControl_press
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_arianjm_tfg_deskvoice_CommandControl
 * Method:    release
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_arianjm_tfg_deskvoice_CommandControl_release
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
